services:
  monotreme:
    image: monotreme:local
    container_name: monotreme
    ports:
      - 5231:5231

    volumes:
      - ./data:/var/opt/monotreme
    restart: unless-stopped
    networks:
      - monotreme-network

networks:
  monotreme-network:
    driver: bridge