// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: api/v1/follow_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Shortcut } from "./shortcut_service";
import { User } from "./user_service";

export const protobufPackage = "monotreme.api.v1";

export interface Following {
  id: number;
  followerId: number;
  followingId: number;
  createdTime?: Date | undefined;
  follower?: User | undefined;
  following?: User | undefined;
}

export interface ListFollowingRequest {
}

export interface ListFollowingResponse {
  following: Following[];
}

export interface FollowUserRequest {
  userId?: number | undefined;
  userEmail?: string | undefined;
}

export interface UnfollowUserRequest {
  id: number;
}

export interface ListFollowersRequest {
}

export interface ListFollowersResponse {
  followers: Following[];
}

export interface ListFollowingUserShortcutsRequest {
  userId: number;
}

export interface ListFollowingUserShortcutsResponse {
  shortcuts: Shortcut[];
}

function createBaseFollowing(): Following {
  return { id: 0, followerId: 0, followingId: 0, createdTime: undefined, follower: undefined, following: undefined };
}

export const Following: MessageFns<Following> = {
  encode(message: Following, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.followerId !== 0) {
      writer.uint32(16).int32(message.followerId);
    }
    if (message.followingId !== 0) {
      writer.uint32(24).int32(message.followingId);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(34).fork()).join();
    }
    if (message.follower !== undefined) {
      User.encode(message.follower, writer.uint32(42).fork()).join();
    }
    if (message.following !== undefined) {
      User.encode(message.following, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Following {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFollowing();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.followerId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.followingId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.follower = User.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.following = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Following>): Following {
    return Following.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Following>): Following {
    const message = createBaseFollowing();
    message.id = object.id ?? 0;
    message.followerId = object.followerId ?? 0;
    message.followingId = object.followingId ?? 0;
    message.createdTime = object.createdTime ?? undefined;
    message.follower = (object.follower !== undefined && object.follower !== null)
      ? User.fromPartial(object.follower)
      : undefined;
    message.following = (object.following !== undefined && object.following !== null)
      ? User.fromPartial(object.following)
      : undefined;
    return message;
  },
};

function createBaseListFollowingRequest(): ListFollowingRequest {
  return {};
}

export const ListFollowingRequest: MessageFns<ListFollowingRequest> = {
  encode(_: ListFollowingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingRequest>): ListFollowingRequest {
    return ListFollowingRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListFollowingRequest>): ListFollowingRequest {
    const message = createBaseListFollowingRequest();
    return message;
  },
};

function createBaseListFollowingResponse(): ListFollowingResponse {
  return { following: [] };
}

export const ListFollowingResponse: MessageFns<ListFollowingResponse> = {
  encode(message: ListFollowingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.following) {
      Following.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.following.push(Following.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingResponse>): ListFollowingResponse {
    return ListFollowingResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowingResponse>): ListFollowingResponse {
    const message = createBaseListFollowingResponse();
    message.following = object.following?.map((e) => Following.fromPartial(e)) || [];
    return message;
  },
};

function createBaseFollowUserRequest(): FollowUserRequest {
  return { userId: undefined, userEmail: undefined };
}

export const FollowUserRequest: MessageFns<FollowUserRequest> = {
  encode(message: FollowUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== undefined) {
      writer.uint32(8).int32(message.userId);
    }
    if (message.userEmail !== undefined) {
      writer.uint32(18).string(message.userEmail);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FollowUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFollowUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<FollowUserRequest>): FollowUserRequest {
    return FollowUserRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<FollowUserRequest>): FollowUserRequest {
    const message = createBaseFollowUserRequest();
    message.userId = object.userId ?? undefined;
    message.userEmail = object.userEmail ?? undefined;
    return message;
  },
};

function createBaseUnfollowUserRequest(): UnfollowUserRequest {
  return { id: 0 };
}

export const UnfollowUserRequest: MessageFns<UnfollowUserRequest> = {
  encode(message: UnfollowUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UnfollowUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUnfollowUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UnfollowUserRequest>): UnfollowUserRequest {
    return UnfollowUserRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UnfollowUserRequest>): UnfollowUserRequest {
    const message = createBaseUnfollowUserRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseListFollowersRequest(): ListFollowersRequest {
  return {};
}

export const ListFollowersRequest: MessageFns<ListFollowersRequest> = {
  encode(_: ListFollowersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowersRequest>): ListFollowersRequest {
    return ListFollowersRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListFollowersRequest>): ListFollowersRequest {
    const message = createBaseListFollowersRequest();
    return message;
  },
};

function createBaseListFollowersResponse(): ListFollowersResponse {
  return { followers: [] };
}

export const ListFollowersResponse: MessageFns<ListFollowersResponse> = {
  encode(message: ListFollowersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.followers) {
      Following.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.followers.push(Following.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowersResponse>): ListFollowersResponse {
    return ListFollowersResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowersResponse>): ListFollowersResponse {
    const message = createBaseListFollowersResponse();
    message.followers = object.followers?.map((e) => Following.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListFollowingUserShortcutsRequest(): ListFollowingUserShortcutsRequest {
  return { userId: 0 };
}

export const ListFollowingUserShortcutsRequest: MessageFns<ListFollowingUserShortcutsRequest> = {
  encode(message: ListFollowingUserShortcutsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== 0) {
      writer.uint32(8).int32(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingUserShortcutsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingUserShortcutsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingUserShortcutsRequest>): ListFollowingUserShortcutsRequest {
    return ListFollowingUserShortcutsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowingUserShortcutsRequest>): ListFollowingUserShortcutsRequest {
    const message = createBaseListFollowingUserShortcutsRequest();
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseListFollowingUserShortcutsResponse(): ListFollowingUserShortcutsResponse {
  return { shortcuts: [] };
}

export const ListFollowingUserShortcutsResponse: MessageFns<ListFollowingUserShortcutsResponse> = {
  encode(message: ListFollowingUserShortcutsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.shortcuts) {
      Shortcut.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFollowingUserShortcutsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFollowingUserShortcutsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shortcuts.push(Shortcut.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFollowingUserShortcutsResponse>): ListFollowingUserShortcutsResponse {
    return ListFollowingUserShortcutsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFollowingUserShortcutsResponse>): ListFollowingUserShortcutsResponse {
    const message = createBaseListFollowingUserShortcutsResponse();
    message.shortcuts = object.shortcuts?.map((e) => Shortcut.fromPartial(e)) || [];
    return message;
  },
};

export type FollowServiceDefinition = typeof FollowServiceDefinition;
export const FollowServiceDefinition = {
  name: "FollowService",
  fullName: "monotreme.api.v1.FollowService",
  methods: {
    /** ListFollowing lists all users that the current user is following */
    listFollowing: {
      name: "ListFollowing",
      requestType: ListFollowingRequest,
      requestStream: false,
      responseType: ListFollowingResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              19,
              18,
              17,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              105,
              110,
              103,
            ]),
          ],
        },
      },
    },
    /** FollowUser follows a user */
    followUser: {
      name: "FollowUser",
      requestType: FollowUserRequest,
      requestStream: false,
      responseType: Following,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              22,
              58,
              1,
              42,
              34,
              17,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              105,
              110,
              103,
            ]),
          ],
        },
      },
    },
    /** UnfollowUser unfollows a user */
    unfollowUser: {
      name: "UnfollowUser",
      requestType: UnfollowUserRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              24,
              42,
              22,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              105,
              110,
              103,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** ListFollowers lists all users following the current user */
    listFollowers: {
      name: "ListFollowers",
      requestType: ListFollowersRequest,
      requestStream: false,
      responseType: ListFollowersResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              19,
              18,
              17,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              101,
              114,
              115,
            ]),
          ],
        },
      },
    },
    /** ListFollowingUserShortcuts lists public shortcuts from users the current user is following */
    listFollowingUserShortcuts: {
      name: "ListFollowingUserShortcuts",
      requestType: ListFollowingUserShortcutsRequest,
      requestStream: false,
      responseType: ListFollowingUserShortcutsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              39,
              18,
              37,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              111,
              108,
              108,
              111,
              119,
              105,
              110,
              103,
              47,
              123,
              117,
              115,
              101,
              114,
              95,
              105,
              100,
              125,
              47,
              115,
              104,
              111,
              114,
              116,
              99,
              117,
              116,
              115,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
