// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: api/v1/friend_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";
import { User } from "./user_service";

export const protobufPackage = "monotreme.api.v1";

export enum FriendshipStatus {
  FRIENDSHIP_STATUS_UNSPECIFIED = "FRIENDSHIP_STATUS_UNSPECIFIED",
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  BLOCKED = "BLOCKED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function friendshipStatusFromJSON(object: any): FriendshipStatus {
  switch (object) {
    case 0:
    case "FRIENDSHIP_STATUS_UNSPECIFIED":
      return FriendshipStatus.FRIENDSHIP_STATUS_UNSPECIFIED;
    case 1:
    case "PENDING":
      return FriendshipStatus.PENDING;
    case 2:
    case "ACCEPTED":
      return FriendshipStatus.ACCEPTED;
    case 3:
    case "DECLINED":
      return FriendshipStatus.DECLINED;
    case 4:
    case "BLOCKED":
      return FriendshipStatus.BLOCKED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FriendshipStatus.UNRECOGNIZED;
  }
}

export function friendshipStatusToNumber(object: FriendshipStatus): number {
  switch (object) {
    case FriendshipStatus.FRIENDSHIP_STATUS_UNSPECIFIED:
      return 0;
    case FriendshipStatus.PENDING:
      return 1;
    case FriendshipStatus.ACCEPTED:
      return 2;
    case FriendshipStatus.DECLINED:
      return 3;
    case FriendshipStatus.BLOCKED:
      return 4;
    case FriendshipStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum FriendRequestType {
  REQUEST_TYPE_ALL = "REQUEST_TYPE_ALL",
  REQUEST_TYPE_INCOMING = "REQUEST_TYPE_INCOMING",
  REQUEST_TYPE_OUTGOING = "REQUEST_TYPE_OUTGOING",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function friendRequestTypeFromJSON(object: any): FriendRequestType {
  switch (object) {
    case 0:
    case "REQUEST_TYPE_ALL":
      return FriendRequestType.REQUEST_TYPE_ALL;
    case 1:
    case "REQUEST_TYPE_INCOMING":
      return FriendRequestType.REQUEST_TYPE_INCOMING;
    case 2:
    case "REQUEST_TYPE_OUTGOING":
      return FriendRequestType.REQUEST_TYPE_OUTGOING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FriendRequestType.UNRECOGNIZED;
  }
}

export function friendRequestTypeToNumber(object: FriendRequestType): number {
  switch (object) {
    case FriendRequestType.REQUEST_TYPE_ALL:
      return 0;
    case FriendRequestType.REQUEST_TYPE_INCOMING:
      return 1;
    case FriendRequestType.REQUEST_TYPE_OUTGOING:
      return 2;
    case FriendRequestType.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface Friendship {
  id: number;
  userId: number;
  friendId: number;
  status: FriendshipStatus;
  createdTime?: Date | undefined;
  acceptedTime?: Date | undefined;
  user?: User | undefined;
  friend?: User | undefined;
}

export interface ListFriendsRequest {
}

export interface ListFriendsResponse {
  friends: Friendship[];
}

export interface SendFriendRequestRequest {
  friendEmail?: string | undefined;
  friendId?: number | undefined;
}

export interface ListFriendRequestsRequest {
  type: FriendRequestType;
}

export interface ListFriendRequestsResponse {
  friendRequests: Friendship[];
}

export interface AcceptFriendRequestRequest {
  id: number;
}

export interface RemoveFriendRequest {
  id: number;
}

function createBaseFriendship(): Friendship {
  return {
    id: 0,
    userId: 0,
    friendId: 0,
    status: FriendshipStatus.FRIENDSHIP_STATUS_UNSPECIFIED,
    createdTime: undefined,
    acceptedTime: undefined,
    user: undefined,
    friend: undefined,
  };
}

export const Friendship: MessageFns<Friendship> = {
  encode(message: Friendship, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int32(message.userId);
    }
    if (message.friendId !== 0) {
      writer.uint32(24).int32(message.friendId);
    }
    if (message.status !== FriendshipStatus.FRIENDSHIP_STATUS_UNSPECIFIED) {
      writer.uint32(32).int32(friendshipStatusToNumber(message.status));
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(42).fork()).join();
    }
    if (message.acceptedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.acceptedTime), writer.uint32(50).fork()).join();
    }
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(58).fork()).join();
    }
    if (message.friend !== undefined) {
      User.encode(message.friend, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Friendship {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFriendship();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.friendId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.status = friendshipStatusFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.acceptedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.friend = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Friendship>): Friendship {
    return Friendship.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Friendship>): Friendship {
    const message = createBaseFriendship();
    message.id = object.id ?? 0;
    message.userId = object.userId ?? 0;
    message.friendId = object.friendId ?? 0;
    message.status = object.status ?? FriendshipStatus.FRIENDSHIP_STATUS_UNSPECIFIED;
    message.createdTime = object.createdTime ?? undefined;
    message.acceptedTime = object.acceptedTime ?? undefined;
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.friend = (object.friend !== undefined && object.friend !== null)
      ? User.fromPartial(object.friend)
      : undefined;
    return message;
  },
};

function createBaseListFriendsRequest(): ListFriendsRequest {
  return {};
}

export const ListFriendsRequest: MessageFns<ListFriendsRequest> = {
  encode(_: ListFriendsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFriendsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFriendsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFriendsRequest>): ListFriendsRequest {
    return ListFriendsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListFriendsRequest>): ListFriendsRequest {
    const message = createBaseListFriendsRequest();
    return message;
  },
};

function createBaseListFriendsResponse(): ListFriendsResponse {
  return { friends: [] };
}

export const ListFriendsResponse: MessageFns<ListFriendsResponse> = {
  encode(message: ListFriendsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.friends) {
      Friendship.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFriendsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFriendsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.friends.push(Friendship.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFriendsResponse>): ListFriendsResponse {
    return ListFriendsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFriendsResponse>): ListFriendsResponse {
    const message = createBaseListFriendsResponse();
    message.friends = object.friends?.map((e) => Friendship.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSendFriendRequestRequest(): SendFriendRequestRequest {
  return { friendEmail: undefined, friendId: undefined };
}

export const SendFriendRequestRequest: MessageFns<SendFriendRequestRequest> = {
  encode(message: SendFriendRequestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.friendEmail !== undefined) {
      writer.uint32(10).string(message.friendEmail);
    }
    if (message.friendId !== undefined) {
      writer.uint32(16).int32(message.friendId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendFriendRequestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendFriendRequestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.friendEmail = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.friendId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SendFriendRequestRequest>): SendFriendRequestRequest {
    return SendFriendRequestRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SendFriendRequestRequest>): SendFriendRequestRequest {
    const message = createBaseSendFriendRequestRequest();
    message.friendEmail = object.friendEmail ?? undefined;
    message.friendId = object.friendId ?? undefined;
    return message;
  },
};

function createBaseListFriendRequestsRequest(): ListFriendRequestsRequest {
  return { type: FriendRequestType.REQUEST_TYPE_ALL };
}

export const ListFriendRequestsRequest: MessageFns<ListFriendRequestsRequest> = {
  encode(message: ListFriendRequestsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== FriendRequestType.REQUEST_TYPE_ALL) {
      writer.uint32(8).int32(friendRequestTypeToNumber(message.type));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFriendRequestsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFriendRequestsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = friendRequestTypeFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFriendRequestsRequest>): ListFriendRequestsRequest {
    return ListFriendRequestsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFriendRequestsRequest>): ListFriendRequestsRequest {
    const message = createBaseListFriendRequestsRequest();
    message.type = object.type ?? FriendRequestType.REQUEST_TYPE_ALL;
    return message;
  },
};

function createBaseListFriendRequestsResponse(): ListFriendRequestsResponse {
  return { friendRequests: [] };
}

export const ListFriendRequestsResponse: MessageFns<ListFriendRequestsResponse> = {
  encode(message: ListFriendRequestsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.friendRequests) {
      Friendship.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListFriendRequestsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListFriendRequestsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.friendRequests.push(Friendship.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListFriendRequestsResponse>): ListFriendRequestsResponse {
    return ListFriendRequestsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListFriendRequestsResponse>): ListFriendRequestsResponse {
    const message = createBaseListFriendRequestsResponse();
    message.friendRequests = object.friendRequests?.map((e) => Friendship.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAcceptFriendRequestRequest(): AcceptFriendRequestRequest {
  return { id: 0 };
}

export const AcceptFriendRequestRequest: MessageFns<AcceptFriendRequestRequest> = {
  encode(message: AcceptFriendRequestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcceptFriendRequestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcceptFriendRequestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AcceptFriendRequestRequest>): AcceptFriendRequestRequest {
    return AcceptFriendRequestRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AcceptFriendRequestRequest>): AcceptFriendRequestRequest {
    const message = createBaseAcceptFriendRequestRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseRemoveFriendRequest(): RemoveFriendRequest {
  return { id: 0 };
}

export const RemoveFriendRequest: MessageFns<RemoveFriendRequest> = {
  encode(message: RemoveFriendRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveFriendRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveFriendRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RemoveFriendRequest>): RemoveFriendRequest {
    return RemoveFriendRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RemoveFriendRequest>): RemoveFriendRequest {
    const message = createBaseRemoveFriendRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

export type FriendServiceDefinition = typeof FriendServiceDefinition;
export const FriendServiceDefinition = {
  name: "FriendService",
  fullName: "monotreme.api.v1.FriendService",
  methods: {
    /** ListFriends returns a list of friends for the current user. */
    listFriends: {
      name: "ListFriends",
      requestType: ListFriendsRequest,
      requestStream: false,
      responseType: ListFriendsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([17, 18, 15, 47, 97, 112, 105, 47, 118, 49, 47, 102, 114, 105, 101, 110, 100, 115]),
          ],
        },
      },
    },
    /** SendFriendRequest sends a friend request to another user. */
    sendFriendRequest: {
      name: "SendFriendRequest",
      requestType: SendFriendRequestRequest,
      requestStream: false,
      responseType: Friendship,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              20,
              58,
              1,
              42,
              34,
              15,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              114,
              105,
              101,
              110,
              100,
              115,
            ]),
          ],
        },
      },
    },
    /** ListFriendRequests returns a list of pending friend requests. */
    listFriendRequests: {
      name: "ListFriendRequests",
      requestType: ListFriendRequestsRequest,
      requestStream: false,
      responseType: ListFriendRequestsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              26,
              18,
              24,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              114,
              105,
              101,
              110,
              100,
              115,
              47,
              114,
              101,
              113,
              117,
              101,
              115,
              116,
              115,
            ]),
          ],
        },
      },
    },
    /** AcceptFriendRequest accepts a pending friend request. */
    acceptFriendRequest: {
      name: "AcceptFriendRequest",
      requestType: AcceptFriendRequestRequest,
      requestStream: false,
      responseType: Friendship,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              32,
              58,
              1,
              42,
              34,
              27,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              114,
              105,
              101,
              110,
              100,
              115,
              47,
              123,
              105,
              100,
              125,
              47,
              97,
              99,
              99,
              101,
              112,
              116,
            ]),
          ],
        },
      },
    },
    /** RemoveFriend removes a friend or declines a friend request. */
    removeFriend: {
      name: "RemoveFriend",
      requestType: RemoveFriendRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              22,
              42,
              20,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              102,
              114,
              105,
              101,
              110,
              100,
              115,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
