// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: api/v1/invitation_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "monotreme.api.v1";

export interface Invitation {
  id: number;
  createdTime?: Date | undefined;
  updatedTime?:
    | Date
    | undefined;
  /** Path to inviting user: "/users/[uuid]" */
  from: string;
  /** Path to invited user: "/users/[uuid]" */
  to: string;
  /** ISO 8601 datetime string */
  acceptedAt: string;
  /** ISO 8601 datetime string */
  deletedAt: string;
}

export interface ListInvitationsRequest {
  /** Optional filter by from user path */
  from: string;
  /** Optional filter by to user path */
  to: string;
  /** Optional filter by accepted status */
  accepted?:
    | boolean
    | undefined;
  /** Optional filter by deleted status */
  deleted?: boolean | undefined;
}

export interface ListInvitationsResponse {
  invitations: Invitation[];
}

export interface GetInvitationRequest {
  id: number;
}

export interface CreateInvitationRequest {
  invitation?: Invitation | undefined;
}

export interface AcceptInvitationRequest {
  id: number;
}

export interface DeleteInvitationRequest {
  id: number;
}

function createBaseInvitation(): Invitation {
  return { id: 0, createdTime: undefined, updatedTime: undefined, from: "", to: "", acceptedAt: "", deletedAt: "" };
}

export const Invitation: MessageFns<Invitation> = {
  encode(message: Invitation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(18).fork()).join();
    }
    if (message.updatedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedTime), writer.uint32(26).fork()).join();
    }
    if (message.from !== "") {
      writer.uint32(34).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(42).string(message.to);
    }
    if (message.acceptedAt !== "") {
      writer.uint32(50).string(message.acceptedAt);
    }
    if (message.deletedAt !== "") {
      writer.uint32(58).string(message.deletedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Invitation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInvitation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.updatedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.acceptedAt = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.deletedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Invitation>): Invitation {
    return Invitation.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Invitation>): Invitation {
    const message = createBaseInvitation();
    message.id = object.id ?? 0;
    message.createdTime = object.createdTime ?? undefined;
    message.updatedTime = object.updatedTime ?? undefined;
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.acceptedAt = object.acceptedAt ?? "";
    message.deletedAt = object.deletedAt ?? "";
    return message;
  },
};

function createBaseListInvitationsRequest(): ListInvitationsRequest {
  return { from: "", to: "", accepted: undefined, deleted: undefined };
}

export const ListInvitationsRequest: MessageFns<ListInvitationsRequest> = {
  encode(message: ListInvitationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    if (message.accepted !== undefined) {
      writer.uint32(24).bool(message.accepted);
    }
    if (message.deleted !== undefined) {
      writer.uint32(32).bool(message.deleted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInvitationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInvitationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.accepted = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.deleted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListInvitationsRequest>): ListInvitationsRequest {
    return ListInvitationsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListInvitationsRequest>): ListInvitationsRequest {
    const message = createBaseListInvitationsRequest();
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.accepted = object.accepted ?? undefined;
    message.deleted = object.deleted ?? undefined;
    return message;
  },
};

function createBaseListInvitationsResponse(): ListInvitationsResponse {
  return { invitations: [] };
}

export const ListInvitationsResponse: MessageFns<ListInvitationsResponse> = {
  encode(message: ListInvitationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.invitations) {
      Invitation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListInvitationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListInvitationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invitations.push(Invitation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListInvitationsResponse>): ListInvitationsResponse {
    return ListInvitationsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListInvitationsResponse>): ListInvitationsResponse {
    const message = createBaseListInvitationsResponse();
    message.invitations = object.invitations?.map((e) => Invitation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetInvitationRequest(): GetInvitationRequest {
  return { id: 0 };
}

export const GetInvitationRequest: MessageFns<GetInvitationRequest> = {
  encode(message: GetInvitationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetInvitationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetInvitationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetInvitationRequest>): GetInvitationRequest {
    return GetInvitationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetInvitationRequest>): GetInvitationRequest {
    const message = createBaseGetInvitationRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseCreateInvitationRequest(): CreateInvitationRequest {
  return { invitation: undefined };
}

export const CreateInvitationRequest: MessageFns<CreateInvitationRequest> = {
  encode(message: CreateInvitationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invitation !== undefined) {
      Invitation.encode(message.invitation, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateInvitationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateInvitationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invitation = Invitation.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateInvitationRequest>): CreateInvitationRequest {
    return CreateInvitationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateInvitationRequest>): CreateInvitationRequest {
    const message = createBaseCreateInvitationRequest();
    message.invitation = (object.invitation !== undefined && object.invitation !== null)
      ? Invitation.fromPartial(object.invitation)
      : undefined;
    return message;
  },
};

function createBaseAcceptInvitationRequest(): AcceptInvitationRequest {
  return { id: 0 };
}

export const AcceptInvitationRequest: MessageFns<AcceptInvitationRequest> = {
  encode(message: AcceptInvitationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AcceptInvitationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAcceptInvitationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AcceptInvitationRequest>): AcceptInvitationRequest {
    return AcceptInvitationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AcceptInvitationRequest>): AcceptInvitationRequest {
    const message = createBaseAcceptInvitationRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseDeleteInvitationRequest(): DeleteInvitationRequest {
  return { id: 0 };
}

export const DeleteInvitationRequest: MessageFns<DeleteInvitationRequest> = {
  encode(message: DeleteInvitationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteInvitationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteInvitationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteInvitationRequest>): DeleteInvitationRequest {
    return DeleteInvitationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteInvitationRequest>): DeleteInvitationRequest {
    const message = createBaseDeleteInvitationRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

export type InvitationServiceDefinition = typeof InvitationServiceDefinition;
export const InvitationServiceDefinition = {
  name: "InvitationService",
  fullName: "monotreme.api.v1.InvitationService",
  methods: {
    /** ListInvitations returns a list of invitations. */
    listInvitations: {
      name: "ListInvitations",
      requestType: ListInvitationsRequest,
      requestStream: false,
      responseType: ListInvitationsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              21,
              18,
              19,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              115,
            ]),
          ],
        },
      },
    },
    /** GetInvitation returns an invitation by id. */
    getInvitation: {
      name: "GetInvitation",
      requestType: GetInvitationRequest,
      requestStream: false,
      responseType: Invitation,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              26,
              18,
              24,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** CreateInvitation creates an invitation. */
    createInvitation: {
      name: "CreateInvitation",
      requestType: CreateInvitationRequest,
      requestStream: false,
      responseType: Invitation,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              33,
              58,
              10,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              34,
              19,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              115,
            ]),
          ],
        },
      },
    },
    /** AcceptInvitation accepts an invitation. */
    acceptInvitation: {
      name: "AcceptInvitation",
      requestType: AcceptInvitationRequest,
      requestStream: false,
      responseType: Invitation,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              36,
              58,
              1,
              42,
              34,
              31,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              105,
              100,
              125,
              47,
              97,
              99,
              99,
              101,
              112,
              116,
            ]),
          ],
        },
      },
    },
    /** DeleteInvitation deletes an invitation by id. */
    deleteInvitation: {
      name: "DeleteInvitation",
      requestType: DeleteInvitationRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              26,
              42,
              24,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              105,
              110,
              118,
              105,
              116,
              97,
              116,
              105,
              111,
              110,
              115,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
