// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: api/v1/rss_import_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { FieldMask } from "../../google/protobuf/field_mask";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Visibility, visibilityFromJSON, visibilityToNumber } from "./common";

export const protobufPackage = "monotreme.api.v1";

export interface RssFeed {
  id: number;
  creatorId: number;
  createdTime?: Date | undefined;
  updatedTime?: Date | undefined;
  title: string;
  url: string;
  description: string;
  /** Import settings */
  autoImport: boolean;
  /** How often to check for updates (in hours) */
  importFrequencyHours: number;
  lastImportTime?:
    | Date
    | undefined;
  /** Shortcut generation settings */
  defaultTags: string[];
  defaultVisibility: Visibility;
  /** Optional prefix for generated shortcut names */
  shortcutPrefix: string;
  /** Status */
  isActive: boolean;
  lastError: string;
  totalImported: number;
}

/** Empty - returns all feeds for the authenticated user */
export interface ListRssFeedsRequest {
}

export interface ListRssFeedsResponse {
  rssFeeds: RssFeed[];
}

export interface GetRssFeedRequest {
  id: number;
}

export interface CreateRssFeedRequest {
  rssFeed?: RssFeed | undefined;
}

export interface UpdateRssFeedRequest {
  rssFeed?: RssFeed | undefined;
  updateMask?: string[] | undefined;
}

export interface DeleteRssFeedRequest {
  id: number;
}

export interface TriggerRssFeedImportRequest {
  id: number;
}

export interface RssFeedImportResponse {
  importedCount: number;
  importedShortcuts: string[];
  errors: string[];
}

function createBaseRssFeed(): RssFeed {
  return {
    id: 0,
    creatorId: 0,
    createdTime: undefined,
    updatedTime: undefined,
    title: "",
    url: "",
    description: "",
    autoImport: false,
    importFrequencyHours: 0,
    lastImportTime: undefined,
    defaultTags: [],
    defaultVisibility: Visibility.VISIBILITY_UNSPECIFIED,
    shortcutPrefix: "",
    isActive: false,
    lastError: "",
    totalImported: 0,
  };
}

export const RssFeed: MessageFns<RssFeed> = {
  encode(message: RssFeed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.creatorId !== 0) {
      writer.uint32(16).int32(message.creatorId);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(26).fork()).join();
    }
    if (message.updatedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedTime), writer.uint32(34).fork()).join();
    }
    if (message.title !== "") {
      writer.uint32(42).string(message.title);
    }
    if (message.url !== "") {
      writer.uint32(50).string(message.url);
    }
    if (message.description !== "") {
      writer.uint32(58).string(message.description);
    }
    if (message.autoImport !== false) {
      writer.uint32(64).bool(message.autoImport);
    }
    if (message.importFrequencyHours !== 0) {
      writer.uint32(72).int32(message.importFrequencyHours);
    }
    if (message.lastImportTime !== undefined) {
      Timestamp.encode(toTimestamp(message.lastImportTime), writer.uint32(82).fork()).join();
    }
    for (const v of message.defaultTags) {
      writer.uint32(90).string(v!);
    }
    if (message.defaultVisibility !== Visibility.VISIBILITY_UNSPECIFIED) {
      writer.uint32(96).int32(visibilityToNumber(message.defaultVisibility));
    }
    if (message.shortcutPrefix !== "") {
      writer.uint32(106).string(message.shortcutPrefix);
    }
    if (message.isActive !== false) {
      writer.uint32(112).bool(message.isActive);
    }
    if (message.lastError !== "") {
      writer.uint32(122).string(message.lastError);
    }
    if (message.totalImported !== 0) {
      writer.uint32(128).int32(message.totalImported);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RssFeed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRssFeed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.creatorId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.updatedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.autoImport = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.importFrequencyHours = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.lastImportTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.defaultTags.push(reader.string());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.defaultVisibility = visibilityFromJSON(reader.int32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.shortcutPrefix = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.totalImported = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RssFeed>): RssFeed {
    return RssFeed.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RssFeed>): RssFeed {
    const message = createBaseRssFeed();
    message.id = object.id ?? 0;
    message.creatorId = object.creatorId ?? 0;
    message.createdTime = object.createdTime ?? undefined;
    message.updatedTime = object.updatedTime ?? undefined;
    message.title = object.title ?? "";
    message.url = object.url ?? "";
    message.description = object.description ?? "";
    message.autoImport = object.autoImport ?? false;
    message.importFrequencyHours = object.importFrequencyHours ?? 0;
    message.lastImportTime = object.lastImportTime ?? undefined;
    message.defaultTags = object.defaultTags?.map((e) => e) || [];
    message.defaultVisibility = object.defaultVisibility ?? Visibility.VISIBILITY_UNSPECIFIED;
    message.shortcutPrefix = object.shortcutPrefix ?? "";
    message.isActive = object.isActive ?? false;
    message.lastError = object.lastError ?? "";
    message.totalImported = object.totalImported ?? 0;
    return message;
  },
};

function createBaseListRssFeedsRequest(): ListRssFeedsRequest {
  return {};
}

export const ListRssFeedsRequest: MessageFns<ListRssFeedsRequest> = {
  encode(_: ListRssFeedsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListRssFeedsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRssFeedsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListRssFeedsRequest>): ListRssFeedsRequest {
    return ListRssFeedsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListRssFeedsRequest>): ListRssFeedsRequest {
    const message = createBaseListRssFeedsRequest();
    return message;
  },
};

function createBaseListRssFeedsResponse(): ListRssFeedsResponse {
  return { rssFeeds: [] };
}

export const ListRssFeedsResponse: MessageFns<ListRssFeedsResponse> = {
  encode(message: ListRssFeedsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rssFeeds) {
      RssFeed.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListRssFeedsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListRssFeedsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rssFeeds.push(RssFeed.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListRssFeedsResponse>): ListRssFeedsResponse {
    return ListRssFeedsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListRssFeedsResponse>): ListRssFeedsResponse {
    const message = createBaseListRssFeedsResponse();
    message.rssFeeds = object.rssFeeds?.map((e) => RssFeed.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetRssFeedRequest(): GetRssFeedRequest {
  return { id: 0 };
}

export const GetRssFeedRequest: MessageFns<GetRssFeedRequest> = {
  encode(message: GetRssFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRssFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRssFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetRssFeedRequest>): GetRssFeedRequest {
    return GetRssFeedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetRssFeedRequest>): GetRssFeedRequest {
    const message = createBaseGetRssFeedRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseCreateRssFeedRequest(): CreateRssFeedRequest {
  return { rssFeed: undefined };
}

export const CreateRssFeedRequest: MessageFns<CreateRssFeedRequest> = {
  encode(message: CreateRssFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rssFeed !== undefined) {
      RssFeed.encode(message.rssFeed, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateRssFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateRssFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rssFeed = RssFeed.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateRssFeedRequest>): CreateRssFeedRequest {
    return CreateRssFeedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateRssFeedRequest>): CreateRssFeedRequest {
    const message = createBaseCreateRssFeedRequest();
    message.rssFeed = (object.rssFeed !== undefined && object.rssFeed !== null)
      ? RssFeed.fromPartial(object.rssFeed)
      : undefined;
    return message;
  },
};

function createBaseUpdateRssFeedRequest(): UpdateRssFeedRequest {
  return { rssFeed: undefined, updateMask: undefined };
}

export const UpdateRssFeedRequest: MessageFns<UpdateRssFeedRequest> = {
  encode(message: UpdateRssFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rssFeed !== undefined) {
      RssFeed.encode(message.rssFeed, writer.uint32(10).fork()).join();
    }
    if (message.updateMask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.updateMask), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateRssFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRssFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rssFeed = RssFeed.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateMask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UpdateRssFeedRequest>): UpdateRssFeedRequest {
    return UpdateRssFeedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateRssFeedRequest>): UpdateRssFeedRequest {
    const message = createBaseUpdateRssFeedRequest();
    message.rssFeed = (object.rssFeed !== undefined && object.rssFeed !== null)
      ? RssFeed.fromPartial(object.rssFeed)
      : undefined;
    message.updateMask = object.updateMask ?? undefined;
    return message;
  },
};

function createBaseDeleteRssFeedRequest(): DeleteRssFeedRequest {
  return { id: 0 };
}

export const DeleteRssFeedRequest: MessageFns<DeleteRssFeedRequest> = {
  encode(message: DeleteRssFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteRssFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteRssFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteRssFeedRequest>): DeleteRssFeedRequest {
    return DeleteRssFeedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteRssFeedRequest>): DeleteRssFeedRequest {
    const message = createBaseDeleteRssFeedRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseTriggerRssFeedImportRequest(): TriggerRssFeedImportRequest {
  return { id: 0 };
}

export const TriggerRssFeedImportRequest: MessageFns<TriggerRssFeedImportRequest> = {
  encode(message: TriggerRssFeedImportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TriggerRssFeedImportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTriggerRssFeedImportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<TriggerRssFeedImportRequest>): TriggerRssFeedImportRequest {
    return TriggerRssFeedImportRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<TriggerRssFeedImportRequest>): TriggerRssFeedImportRequest {
    const message = createBaseTriggerRssFeedImportRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseRssFeedImportResponse(): RssFeedImportResponse {
  return { importedCount: 0, importedShortcuts: [], errors: [] };
}

export const RssFeedImportResponse: MessageFns<RssFeedImportResponse> = {
  encode(message: RssFeedImportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.importedCount !== 0) {
      writer.uint32(8).int32(message.importedCount);
    }
    for (const v of message.importedShortcuts) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.errors) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RssFeedImportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRssFeedImportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.importedCount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.importedShortcuts.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errors.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RssFeedImportResponse>): RssFeedImportResponse {
    return RssFeedImportResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RssFeedImportResponse>): RssFeedImportResponse {
    const message = createBaseRssFeedImportResponse();
    message.importedCount = object.importedCount ?? 0;
    message.importedShortcuts = object.importedShortcuts?.map((e) => e) || [];
    message.errors = object.errors?.map((e) => e) || [];
    return message;
  },
};

export type RssImportServiceDefinition = typeof RssImportServiceDefinition;
export const RssImportServiceDefinition = {
  name: "RssImportService",
  fullName: "monotreme.api.v1.RssImportService",
  methods: {
    /** ListRssFeeds returns a list of RSS feeds. */
    listRssFeeds: {
      name: "ListRssFeeds",
      requestType: ListRssFeedsRequest,
      requestStream: false,
      responseType: ListRssFeedsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([19, 18, 17, 47, 97, 112, 105, 47, 118, 49, 47, 114, 115, 115, 45, 102, 101, 101, 100, 115]),
          ],
        },
      },
    },
    /** GetRssFeed returns an RSS feed by id. */
    getRssFeed: {
      name: "GetRssFeed",
      requestType: GetRssFeedRequest,
      requestStream: false,
      responseType: RssFeed,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              24,
              18,
              22,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              114,
              115,
              115,
              45,
              102,
              101,
              101,
              100,
              115,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** CreateRssFeed creates a new RSS feed. */
    createRssFeed: {
      name: "CreateRssFeed",
      requestType: CreateRssFeedRequest,
      requestStream: false,
      responseType: RssFeed,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([8, 114, 115, 115, 95, 102, 101, 101, 100])],
          578365826: [
            new Uint8Array([
              29,
              58,
              8,
              114,
              115,
              115,
              95,
              102,
              101,
              101,
              100,
              34,
              17,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              114,
              115,
              115,
              45,
              102,
              101,
              101,
              100,
              115,
            ]),
          ],
        },
      },
    },
    /** UpdateRssFeed updates an RSS feed. */
    updateRssFeed: {
      name: "UpdateRssFeed",
      requestType: UpdateRssFeedRequest,
      requestStream: false,
      responseType: RssFeed,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [
            new Uint8Array([
              20,
              114,
              115,
              115,
              95,
              102,
              101,
              101,
              100,
              44,
              117,
              112,
              100,
              97,
              116,
              101,
              95,
              109,
              97,
              115,
              107,
            ]),
          ],
          578365826: [
            new Uint8Array([
              43,
              58,
              8,
              114,
              115,
              115,
              95,
              102,
              101,
              101,
              100,
              26,
              31,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              114,
              115,
              115,
              45,
              102,
              101,
              101,
              100,
              115,
              47,
              123,
              114,
              115,
              115,
              95,
              102,
              101,
              101,
              100,
              46,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** DeleteRssFeed deletes an RSS feed. */
    deleteRssFeed: {
      name: "DeleteRssFeed",
      requestType: DeleteRssFeedRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              24,
              42,
              22,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              114,
              115,
              115,
              45,
              102,
              101,
              101,
              100,
              115,
              47,
              123,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** TriggerRssFeedImport manually triggers an import for an RSS feed. */
    triggerRssFeedImport: {
      name: "TriggerRssFeedImport",
      requestType: TriggerRssFeedImportRequest,
      requestStream: false,
      responseType: RssFeedImportResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([2, 105, 100])],
          578365826: [
            new Uint8Array([
              31,
              34,
              29,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              114,
              115,
              115,
              45,
              102,
              101,
              101,
              100,
              115,
              47,
              123,
              105,
              100,
              125,
              47,
              105,
              109,
              112,
              111,
              114,
              116,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
