// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: api/v1/tag_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "../../google/protobuf/empty";
import { Timestamp } from "../../google/protobuf/timestamp";
import { Shortcut } from "./shortcut_service";

export const protobufPackage = "monotreme.api.v1";

export interface Tag {
  uuid: string;
  creatorId: number;
  createdTime?: Date | undefined;
  updatedTime?: Date | undefined;
  name: string;
  abbreviation: string;
  description: string;
}

export interface ListTagsRequest {
}

export interface ListTagsResponse {
  tags: Tag[];
}

export interface GetTagRequest {
  uuid: string;
}

export interface GetTagByAbbreviationRequest {
  abbreviation: string;
}

export interface CreateTagRequest {
  tag?: Tag | undefined;
}

export interface UpdateTagRequest {
  tag?: Tag | undefined;
  updateMask: string[];
}

export interface DeleteTagRequest {
  uuid: string;
}

export interface AddBookmarkToTagRequest {
  tagUuid: string;
  shortcutId: number;
}

export interface RemoveBookmarkFromTagRequest {
  tagUuid: string;
  shortcutId: number;
}

export interface ListBookmarksForTagRequest {
  tagUuid: string;
}

export interface ListBookmarksForTagResponse {
  shortcuts: Shortcut[];
}

export interface ListTagsForBookmarkRequest {
  shortcutId: number;
}

export interface ListTagsForBookmarkResponse {
  tags: Tag[];
}

function createBaseTag(): Tag {
  return {
    uuid: "",
    creatorId: 0,
    createdTime: undefined,
    updatedTime: undefined,
    name: "",
    abbreviation: "",
    description: "",
  };
}

export const Tag: MessageFns<Tag> = {
  encode(message: Tag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    if (message.creatorId !== 0) {
      writer.uint32(16).int32(message.creatorId);
    }
    if (message.createdTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTime), writer.uint32(26).fork()).join();
    }
    if (message.updatedTime !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedTime), writer.uint32(34).fork()).join();
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.abbreviation !== "") {
      writer.uint32(50).string(message.abbreviation);
    }
    if (message.description !== "") {
      writer.uint32(58).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.creatorId = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.updatedTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.abbreviation = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Tag>): Tag {
    return Tag.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Tag>): Tag {
    const message = createBaseTag();
    message.uuid = object.uuid ?? "";
    message.creatorId = object.creatorId ?? 0;
    message.createdTime = object.createdTime ?? undefined;
    message.updatedTime = object.updatedTime ?? undefined;
    message.name = object.name ?? "";
    message.abbreviation = object.abbreviation ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseListTagsRequest(): ListTagsRequest {
  return {};
}

export const ListTagsRequest: MessageFns<ListTagsRequest> = {
  encode(_: ListTagsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTagsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTagsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListTagsRequest>): ListTagsRequest {
    return ListTagsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<ListTagsRequest>): ListTagsRequest {
    const message = createBaseListTagsRequest();
    return message;
  },
};

function createBaseListTagsResponse(): ListTagsResponse {
  return { tags: [] };
}

export const ListTagsResponse: MessageFns<ListTagsResponse> = {
  encode(message: ListTagsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tags) {
      Tag.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTagsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTagsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tags.push(Tag.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListTagsResponse>): ListTagsResponse {
    return ListTagsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListTagsResponse>): ListTagsResponse {
    const message = createBaseListTagsResponse();
    message.tags = object.tags?.map((e) => Tag.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetTagRequest(): GetTagRequest {
  return { uuid: "" };
}

export const GetTagRequest: MessageFns<GetTagRequest> = {
  encode(message: GetTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetTagRequest>): GetTagRequest {
    return GetTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTagRequest>): GetTagRequest {
    const message = createBaseGetTagRequest();
    message.uuid = object.uuid ?? "";
    return message;
  },
};

function createBaseGetTagByAbbreviationRequest(): GetTagByAbbreviationRequest {
  return { abbreviation: "" };
}

export const GetTagByAbbreviationRequest: MessageFns<GetTagByAbbreviationRequest> = {
  encode(message: GetTagByAbbreviationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.abbreviation !== "") {
      writer.uint32(10).string(message.abbreviation);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTagByAbbreviationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTagByAbbreviationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.abbreviation = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetTagByAbbreviationRequest>): GetTagByAbbreviationRequest {
    return GetTagByAbbreviationRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetTagByAbbreviationRequest>): GetTagByAbbreviationRequest {
    const message = createBaseGetTagByAbbreviationRequest();
    message.abbreviation = object.abbreviation ?? "";
    return message;
  },
};

function createBaseCreateTagRequest(): CreateTagRequest {
  return { tag: undefined };
}

export const CreateTagRequest: MessageFns<CreateTagRequest> = {
  encode(message: CreateTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tag !== undefined) {
      Tag.encode(message.tag, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tag = Tag.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<CreateTagRequest>): CreateTagRequest {
    return CreateTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateTagRequest>): CreateTagRequest {
    const message = createBaseCreateTagRequest();
    message.tag = (object.tag !== undefined && object.tag !== null) ? Tag.fromPartial(object.tag) : undefined;
    return message;
  },
};

function createBaseUpdateTagRequest(): UpdateTagRequest {
  return { tag: undefined, updateMask: [] };
}

export const UpdateTagRequest: MessageFns<UpdateTagRequest> = {
  encode(message: UpdateTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tag !== undefined) {
      Tag.encode(message.tag, writer.uint32(10).fork()).join();
    }
    for (const v of message.updateMask) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tag = Tag.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateMask.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UpdateTagRequest>): UpdateTagRequest {
    return UpdateTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateTagRequest>): UpdateTagRequest {
    const message = createBaseUpdateTagRequest();
    message.tag = (object.tag !== undefined && object.tag !== null) ? Tag.fromPartial(object.tag) : undefined;
    message.updateMask = object.updateMask?.map((e) => e) || [];
    return message;
  },
};

function createBaseDeleteTagRequest(): DeleteTagRequest {
  return { uuid: "" };
}

export const DeleteTagRequest: MessageFns<DeleteTagRequest> = {
  encode(message: DeleteTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uuid !== "") {
      writer.uint32(10).string(message.uuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DeleteTagRequest>): DeleteTagRequest {
    return DeleteTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteTagRequest>): DeleteTagRequest {
    const message = createBaseDeleteTagRequest();
    message.uuid = object.uuid ?? "";
    return message;
  },
};

function createBaseAddBookmarkToTagRequest(): AddBookmarkToTagRequest {
  return { tagUuid: "", shortcutId: 0 };
}

export const AddBookmarkToTagRequest: MessageFns<AddBookmarkToTagRequest> = {
  encode(message: AddBookmarkToTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tagUuid !== "") {
      writer.uint32(10).string(message.tagUuid);
    }
    if (message.shortcutId !== 0) {
      writer.uint32(16).int32(message.shortcutId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddBookmarkToTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddBookmarkToTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tagUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shortcutId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AddBookmarkToTagRequest>): AddBookmarkToTagRequest {
    return AddBookmarkToTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AddBookmarkToTagRequest>): AddBookmarkToTagRequest {
    const message = createBaseAddBookmarkToTagRequest();
    message.tagUuid = object.tagUuid ?? "";
    message.shortcutId = object.shortcutId ?? 0;
    return message;
  },
};

function createBaseRemoveBookmarkFromTagRequest(): RemoveBookmarkFromTagRequest {
  return { tagUuid: "", shortcutId: 0 };
}

export const RemoveBookmarkFromTagRequest: MessageFns<RemoveBookmarkFromTagRequest> = {
  encode(message: RemoveBookmarkFromTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tagUuid !== "") {
      writer.uint32(10).string(message.tagUuid);
    }
    if (message.shortcutId !== 0) {
      writer.uint32(16).int32(message.shortcutId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveBookmarkFromTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveBookmarkFromTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tagUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shortcutId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RemoveBookmarkFromTagRequest>): RemoveBookmarkFromTagRequest {
    return RemoveBookmarkFromTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RemoveBookmarkFromTagRequest>): RemoveBookmarkFromTagRequest {
    const message = createBaseRemoveBookmarkFromTagRequest();
    message.tagUuid = object.tagUuid ?? "";
    message.shortcutId = object.shortcutId ?? 0;
    return message;
  },
};

function createBaseListBookmarksForTagRequest(): ListBookmarksForTagRequest {
  return { tagUuid: "" };
}

export const ListBookmarksForTagRequest: MessageFns<ListBookmarksForTagRequest> = {
  encode(message: ListBookmarksForTagRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tagUuid !== "") {
      writer.uint32(10).string(message.tagUuid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBookmarksForTagRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBookmarksForTagRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tagUuid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListBookmarksForTagRequest>): ListBookmarksForTagRequest {
    return ListBookmarksForTagRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListBookmarksForTagRequest>): ListBookmarksForTagRequest {
    const message = createBaseListBookmarksForTagRequest();
    message.tagUuid = object.tagUuid ?? "";
    return message;
  },
};

function createBaseListBookmarksForTagResponse(): ListBookmarksForTagResponse {
  return { shortcuts: [] };
}

export const ListBookmarksForTagResponse: MessageFns<ListBookmarksForTagResponse> = {
  encode(message: ListBookmarksForTagResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.shortcuts) {
      Shortcut.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBookmarksForTagResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBookmarksForTagResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.shortcuts.push(Shortcut.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListBookmarksForTagResponse>): ListBookmarksForTagResponse {
    return ListBookmarksForTagResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListBookmarksForTagResponse>): ListBookmarksForTagResponse {
    const message = createBaseListBookmarksForTagResponse();
    message.shortcuts = object.shortcuts?.map((e) => Shortcut.fromPartial(e)) || [];
    return message;
  },
};

function createBaseListTagsForBookmarkRequest(): ListTagsForBookmarkRequest {
  return { shortcutId: 0 };
}

export const ListTagsForBookmarkRequest: MessageFns<ListTagsForBookmarkRequest> = {
  encode(message: ListTagsForBookmarkRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shortcutId !== 0) {
      writer.uint32(8).int32(message.shortcutId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTagsForBookmarkRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTagsForBookmarkRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.shortcutId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListTagsForBookmarkRequest>): ListTagsForBookmarkRequest {
    return ListTagsForBookmarkRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListTagsForBookmarkRequest>): ListTagsForBookmarkRequest {
    const message = createBaseListTagsForBookmarkRequest();
    message.shortcutId = object.shortcutId ?? 0;
    return message;
  },
};

function createBaseListTagsForBookmarkResponse(): ListTagsForBookmarkResponse {
  return { tags: [] };
}

export const ListTagsForBookmarkResponse: MessageFns<ListTagsForBookmarkResponse> = {
  encode(message: ListTagsForBookmarkResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tags) {
      Tag.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTagsForBookmarkResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTagsForBookmarkResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tags.push(Tag.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ListTagsForBookmarkResponse>): ListTagsForBookmarkResponse {
    return ListTagsForBookmarkResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListTagsForBookmarkResponse>): ListTagsForBookmarkResponse {
    const message = createBaseListTagsForBookmarkResponse();
    message.tags = object.tags?.map((e) => Tag.fromPartial(e)) || [];
    return message;
  },
};

export type TagServiceDefinition = typeof TagServiceDefinition;
export const TagServiceDefinition = {
  name: "TagService",
  fullName: "monotreme.api.v1.TagService",
  methods: {
    /** ListTags returns a list of tags. */
    listTags: {
      name: "ListTags",
      requestType: ListTagsRequest,
      requestStream: false,
      responseType: ListTagsResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [new Uint8Array([14, 18, 12, 47, 97, 112, 105, 47, 118, 49, 47, 116, 97, 103, 115])],
        },
      },
    },
    /** GetTag returns a tag by uuid. */
    getTag: {
      name: "GetTag",
      requestType: GetTagRequest,
      requestStream: false,
      responseType: Tag,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([4, 117, 117, 105, 100])],
          578365826: [
            new Uint8Array([
              21,
              18,
              19,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              117,
              117,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** GetTagByAbbreviation returns a tag by abbreviation. */
    getTagByAbbreviation: {
      name: "GetTagByAbbreviation",
      requestType: GetTagByAbbreviationRequest,
      requestStream: false,
      responseType: Tag,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([12, 97, 98, 98, 114, 101, 118, 105, 97, 116, 105, 111, 110])],
          578365826: [
            new Uint8Array([
              34,
              18,
              32,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              97,
              98,
              98,
              114,
              47,
              123,
              97,
              98,
              98,
              114,
              101,
              118,
              105,
              97,
              116,
              105,
              111,
              110,
              125,
            ]),
          ],
        },
      },
    },
    /** CreateTag creates a tag. */
    createTag: {
      name: "CreateTag",
      requestType: CreateTagRequest,
      requestStream: false,
      responseType: Tag,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([19, 58, 3, 116, 97, 103, 34, 12, 47, 97, 112, 105, 47, 118, 49, 47, 116, 97, 103, 115]),
          ],
        },
      },
    },
    /** UpdateTag updates a tag. */
    updateTag: {
      name: "UpdateTag",
      requestType: UpdateTagRequest,
      requestStream: false,
      responseType: Tag,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([15, 116, 97, 103, 44, 117, 112, 100, 97, 116, 101, 95, 109, 97, 115, 107])],
          578365826: [
            new Uint8Array([
              30,
              58,
              3,
              116,
              97,
              103,
              26,
              23,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              116,
              97,
              103,
              46,
              117,
              117,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** DeleteTag deletes a tag by uuid. */
    deleteTag: {
      name: "DeleteTag",
      requestType: DeleteTagRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [new Uint8Array([4, 117, 117, 105, 100])],
          578365826: [
            new Uint8Array([
              21,
              42,
              19,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              117,
              117,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** AddBookmarkToTag adds a bookmark to a tag. */
    addBookmarkToTag: {
      name: "AddBookmarkToTag",
      requestType: AddBookmarkToTagRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              49,
              34,
              47,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              116,
              97,
              103,
              95,
              117,
              117,
              105,
              100,
              125,
              47,
              98,
              111,
              111,
              107,
              109,
              97,
              114,
              107,
              115,
              47,
              123,
              115,
              104,
              111,
              114,
              116,
              99,
              117,
              116,
              95,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** RemoveBookmarkFromTag removes a bookmark from a tag. */
    removeBookmarkFromTag: {
      name: "RemoveBookmarkFromTag",
      requestType: RemoveBookmarkFromTagRequest,
      requestStream: false,
      responseType: Empty,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              49,
              42,
              47,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              116,
              97,
              103,
              95,
              117,
              117,
              105,
              100,
              125,
              47,
              98,
              111,
              111,
              107,
              109,
              97,
              114,
              107,
              115,
              47,
              123,
              115,
              104,
              111,
              114,
              116,
              99,
              117,
              116,
              95,
              105,
              100,
              125,
            ]),
          ],
        },
      },
    },
    /** ListBookmarksForTag lists all bookmarks for a tag. */
    listBookmarksForTag: {
      name: "ListBookmarksForTag",
      requestType: ListBookmarksForTagRequest,
      requestStream: false,
      responseType: ListBookmarksForTagResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              35,
              18,
              33,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              116,
              97,
              103,
              115,
              47,
              123,
              116,
              97,
              103,
              95,
              117,
              117,
              105,
              100,
              125,
              47,
              98,
              111,
              111,
              107,
              109,
              97,
              114,
              107,
              115,
            ]),
          ],
        },
      },
    },
    /** ListTagsForBookmark lists all tags for a bookmark. */
    listTagsForBookmark: {
      name: "ListTagsForBookmark",
      requestType: ListTagsForBookmarkRequest,
      requestStream: false,
      responseType: ListTagsForBookmarkResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              38,
              18,
              36,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              98,
              111,
              111,
              107,
              109,
              97,
              114,
              107,
              115,
              47,
              123,
              115,
              104,
              111,
              114,
              116,
              99,
              117,
              116,
              95,
              105,
              100,
              125,
              47,
              116,
              97,
              103,
              115,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
