// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: api/v1/workspace_service.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { FieldMask } from "../../google/protobuf/field_mask";
import { Visibility, visibilityFromJSON, visibilityToNumber } from "./common";
import { Subscription } from "./subscription_service";

export const protobufPackage = "monotreme.api.v1";

export interface WorkspaceProfile {
  /** Current workspace mode: dev, prod. */
  mode: string;
  /** Current workspace version. */
  version: string;
  /**
   * The owner name.
   * Format: "users/{id}"
   */
  owner: string;
  /** The workspace subscription. */
  subscription?:
    | Subscription
    | undefined;
  /** The custom style. */
  customStyle: string;
  /** The workspace branding. */
  branding: Uint8Array;
}

export interface WorkspaceSetting {
  /** The url of instance. */
  instanceUrl: string;
  /** The workspace custome branding. */
  branding: Uint8Array;
  /** The custom style. */
  customStyle: string;
  /** The default visibility of shortcuts and collections. */
  defaultVisibility: Visibility;
  /** The identity providers. */
  identityProviders: IdentityProvider[];
  /** Whether to disallow user registration by email&password. */
  disallowUserRegistration: boolean;
  /** Whether to disallow password authentication. */
  disallowPasswordAuth: boolean;
  /** The prefix used for shortcut URLs (e.g. "s" for "/s/shortcut-name"). */
  shortcutPrefix: string;
}

export interface IdentityProvider {
  /** The unique identifier of the identity provider. */
  id: string;
  title: string;
  type: IdentityProvider_Type;
  config?: IdentityProviderConfig | undefined;
}

export enum IdentityProvider_Type {
  TYPE_UNSPECIFIED = "TYPE_UNSPECIFIED",
  OAUTH2 = "OAUTH2",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function identityProvider_TypeFromJSON(object: any): IdentityProvider_Type {
  switch (object) {
    case 0:
    case "TYPE_UNSPECIFIED":
      return IdentityProvider_Type.TYPE_UNSPECIFIED;
    case 1:
    case "OAUTH2":
      return IdentityProvider_Type.OAUTH2;
    case -1:
    case "UNRECOGNIZED":
    default:
      return IdentityProvider_Type.UNRECOGNIZED;
  }
}

export function identityProvider_TypeToNumber(object: IdentityProvider_Type): number {
  switch (object) {
    case IdentityProvider_Type.TYPE_UNSPECIFIED:
      return 0;
    case IdentityProvider_Type.OAUTH2:
      return 1;
    case IdentityProvider_Type.UNRECOGNIZED:
    default:
      return -1;
  }
}

export interface IdentityProviderConfig {
  oauth2?: IdentityProviderConfig_OAuth2Config | undefined;
}

export interface IdentityProviderConfig_FieldMapping {
  identifier: string;
  displayName: string;
}

export interface IdentityProviderConfig_OAuth2Config {
  clientId: string;
  clientSecret: string;
  authUrl: string;
  tokenUrl: string;
  userInfoUrl: string;
  scopes: string[];
  fieldMapping?: IdentityProviderConfig_FieldMapping | undefined;
}

export interface GetWorkspaceProfileRequest {
}

export interface GetWorkspaceSettingRequest {
}

export interface UpdateWorkspaceSettingRequest {
  /** The user setting. */
  setting?:
    | WorkspaceSetting
    | undefined;
  /** The update mask. */
  updateMask?: string[] | undefined;
}

export interface GetWorkspaceStatsRequest {
}

export interface WorkspaceStats {
  /** Total number of shortcuts in the system */
  totalShortcuts: number;
  /** Total number of users in the system */
  totalUsers: number;
  /** Total number of collections in the system */
  totalCollections: number;
  /** Total number of hits from all shortcuts in the system */
  totalHits: number;
  /** Historical measurements for sparkline graphs (last 100 measurements) */
  historicalData: StatsMeasurement[];
}

export interface StatsMeasurement {
  /** Unix timestamp when the measurement was taken */
  measuredTs: number;
  /** Total number of shortcuts at measurement time */
  shortcutsCount: number;
  /** Total number of users at measurement time */
  usersCount: number;
  /** Total number of collections at measurement time */
  collectionsCount: number;
  /** Total number of hits (shortcut views) at measurement time */
  hitsCount: number;
}

export interface GetDatabaseStatsRequest {
}

export interface DatabaseStats {
  /** Total number of users */
  users: number;
  /** Total number of shortcuts */
  shortcuts: number;
  /** Total number of collections */
  collections: number;
  /** Total number of tags */
  tags: number;
  /** Total number of bookmark-tag relationships */
  bookmarkTags: number;
  /** Total number of friendships */
  friendships: number;
  /** Total number of following relationships */
  followings: number;
  /** Total number of activities */
  activities: number;
  /** Total number of invitations */
  invitations: number;
}

export interface ExportDatabaseRequest {
  /** List of entity types to export */
  entities: string[];
}

export interface ExportDatabaseResponse {
  /** JSON data containing the exported entities */
  data: string;
  /** Filename for the export */
  filename: string;
}

export interface ImportDatabaseRequest {
  /** JSON data to import */
  data: string;
  /** List of entity types to import */
  entities: string[];
  /** Import mode: "new-only", "overwrite", "wipe-and-import" */
  mode: string;
}

export interface ImportDatabaseResponse {
  /** Number of records imported per entity type */
  importedCounts: { [key: string]: number };
  /** Any warnings or messages */
  messages: string[];
}

export interface ImportDatabaseResponse_ImportedCountsEntry {
  key: string;
  value: number;
}

export interface GetDatabaseReportRequest {
  /** Entity type: users, shortcuts, collections, tags, bookmark_tags, friendships, followings, activities, invitations */
  entity: string;
  /** Optional: limit the number of records returned */
  limit?:
    | number
    | undefined;
  /** Optional: offset for pagination */
  offset?: number | undefined;
}

export interface GetDatabaseReportResponse {
  /** The entity type */
  entity: string;
  /** Total count of records */
  totalCount: number;
  /** JSON data containing the records */
  data: string;
  /** Metadata about the report */
  metadata: { [key: string]: string };
}

export interface GetDatabaseReportResponse_MetadataEntry {
  key: string;
  value: string;
}

function createBaseWorkspaceProfile(): WorkspaceProfile {
  return { mode: "", version: "", owner: "", subscription: undefined, customStyle: "", branding: new Uint8Array(0) };
}

export const WorkspaceProfile: MessageFns<WorkspaceProfile> = {
  encode(message: WorkspaceProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mode !== "") {
      writer.uint32(10).string(message.mode);
    }
    if (message.version !== "") {
      writer.uint32(18).string(message.version);
    }
    if (message.owner !== "") {
      writer.uint32(26).string(message.owner);
    }
    if (message.subscription !== undefined) {
      Subscription.encode(message.subscription, writer.uint32(34).fork()).join();
    }
    if (message.customStyle !== "") {
      writer.uint32(42).string(message.customStyle);
    }
    if (message.branding.length !== 0) {
      writer.uint32(50).bytes(message.branding);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkspaceProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkspaceProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subscription = Subscription.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.customStyle = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.branding = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkspaceProfile>): WorkspaceProfile {
    return WorkspaceProfile.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkspaceProfile>): WorkspaceProfile {
    const message = createBaseWorkspaceProfile();
    message.mode = object.mode ?? "";
    message.version = object.version ?? "";
    message.owner = object.owner ?? "";
    message.subscription = (object.subscription !== undefined && object.subscription !== null)
      ? Subscription.fromPartial(object.subscription)
      : undefined;
    message.customStyle = object.customStyle ?? "";
    message.branding = object.branding ?? new Uint8Array(0);
    return message;
  },
};

function createBaseWorkspaceSetting(): WorkspaceSetting {
  return {
    instanceUrl: "",
    branding: new Uint8Array(0),
    customStyle: "",
    defaultVisibility: Visibility.VISIBILITY_UNSPECIFIED,
    identityProviders: [],
    disallowUserRegistration: false,
    disallowPasswordAuth: false,
    shortcutPrefix: "",
  };
}

export const WorkspaceSetting: MessageFns<WorkspaceSetting> = {
  encode(message: WorkspaceSetting, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.instanceUrl !== "") {
      writer.uint32(10).string(message.instanceUrl);
    }
    if (message.branding.length !== 0) {
      writer.uint32(18).bytes(message.branding);
    }
    if (message.customStyle !== "") {
      writer.uint32(26).string(message.customStyle);
    }
    if (message.defaultVisibility !== Visibility.VISIBILITY_UNSPECIFIED) {
      writer.uint32(32).int32(visibilityToNumber(message.defaultVisibility));
    }
    for (const v of message.identityProviders) {
      IdentityProvider.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.disallowUserRegistration !== false) {
      writer.uint32(48).bool(message.disallowUserRegistration);
    }
    if (message.disallowPasswordAuth !== false) {
      writer.uint32(56).bool(message.disallowPasswordAuth);
    }
    if (message.shortcutPrefix !== "") {
      writer.uint32(66).string(message.shortcutPrefix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkspaceSetting {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkspaceSetting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.instanceUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.branding = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.customStyle = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.defaultVisibility = visibilityFromJSON(reader.int32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.identityProviders.push(IdentityProvider.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.disallowUserRegistration = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.disallowPasswordAuth = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.shortcutPrefix = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkspaceSetting>): WorkspaceSetting {
    return WorkspaceSetting.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkspaceSetting>): WorkspaceSetting {
    const message = createBaseWorkspaceSetting();
    message.instanceUrl = object.instanceUrl ?? "";
    message.branding = object.branding ?? new Uint8Array(0);
    message.customStyle = object.customStyle ?? "";
    message.defaultVisibility = object.defaultVisibility ?? Visibility.VISIBILITY_UNSPECIFIED;
    message.identityProviders = object.identityProviders?.map((e) => IdentityProvider.fromPartial(e)) || [];
    message.disallowUserRegistration = object.disallowUserRegistration ?? false;
    message.disallowPasswordAuth = object.disallowPasswordAuth ?? false;
    message.shortcutPrefix = object.shortcutPrefix ?? "";
    return message;
  },
};

function createBaseIdentityProvider(): IdentityProvider {
  return { id: "", title: "", type: IdentityProvider_Type.TYPE_UNSPECIFIED, config: undefined };
}

export const IdentityProvider: MessageFns<IdentityProvider> = {
  encode(message: IdentityProvider, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.type !== IdentityProvider_Type.TYPE_UNSPECIFIED) {
      writer.uint32(24).int32(identityProvider_TypeToNumber(message.type));
    }
    if (message.config !== undefined) {
      IdentityProviderConfig.encode(message.config, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityProvider {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentityProvider();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = identityProvider_TypeFromJSON(reader.int32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.config = IdentityProviderConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IdentityProvider>): IdentityProvider {
    return IdentityProvider.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IdentityProvider>): IdentityProvider {
    const message = createBaseIdentityProvider();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.type = object.type ?? IdentityProvider_Type.TYPE_UNSPECIFIED;
    message.config = (object.config !== undefined && object.config !== null)
      ? IdentityProviderConfig.fromPartial(object.config)
      : undefined;
    return message;
  },
};

function createBaseIdentityProviderConfig(): IdentityProviderConfig {
  return { oauth2: undefined };
}

export const IdentityProviderConfig: MessageFns<IdentityProviderConfig> = {
  encode(message: IdentityProviderConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.oauth2 !== undefined) {
      IdentityProviderConfig_OAuth2Config.encode(message.oauth2, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityProviderConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentityProviderConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.oauth2 = IdentityProviderConfig_OAuth2Config.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IdentityProviderConfig>): IdentityProviderConfig {
    return IdentityProviderConfig.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IdentityProviderConfig>): IdentityProviderConfig {
    const message = createBaseIdentityProviderConfig();
    message.oauth2 = (object.oauth2 !== undefined && object.oauth2 !== null)
      ? IdentityProviderConfig_OAuth2Config.fromPartial(object.oauth2)
      : undefined;
    return message;
  },
};

function createBaseIdentityProviderConfig_FieldMapping(): IdentityProviderConfig_FieldMapping {
  return { identifier: "", displayName: "" };
}

export const IdentityProviderConfig_FieldMapping: MessageFns<IdentityProviderConfig_FieldMapping> = {
  encode(message: IdentityProviderConfig_FieldMapping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    if (message.displayName !== "") {
      writer.uint32(18).string(message.displayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityProviderConfig_FieldMapping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentityProviderConfig_FieldMapping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IdentityProviderConfig_FieldMapping>): IdentityProviderConfig_FieldMapping {
    return IdentityProviderConfig_FieldMapping.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IdentityProviderConfig_FieldMapping>): IdentityProviderConfig_FieldMapping {
    const message = createBaseIdentityProviderConfig_FieldMapping();
    message.identifier = object.identifier ?? "";
    message.displayName = object.displayName ?? "";
    return message;
  },
};

function createBaseIdentityProviderConfig_OAuth2Config(): IdentityProviderConfig_OAuth2Config {
  return {
    clientId: "",
    clientSecret: "",
    authUrl: "",
    tokenUrl: "",
    userInfoUrl: "",
    scopes: [],
    fieldMapping: undefined,
  };
}

export const IdentityProviderConfig_OAuth2Config: MessageFns<IdentityProviderConfig_OAuth2Config> = {
  encode(message: IdentityProviderConfig_OAuth2Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.clientSecret !== "") {
      writer.uint32(18).string(message.clientSecret);
    }
    if (message.authUrl !== "") {
      writer.uint32(26).string(message.authUrl);
    }
    if (message.tokenUrl !== "") {
      writer.uint32(34).string(message.tokenUrl);
    }
    if (message.userInfoUrl !== "") {
      writer.uint32(42).string(message.userInfoUrl);
    }
    for (const v of message.scopes) {
      writer.uint32(50).string(v!);
    }
    if (message.fieldMapping !== undefined) {
      IdentityProviderConfig_FieldMapping.encode(message.fieldMapping, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IdentityProviderConfig_OAuth2Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIdentityProviderConfig_OAuth2Config();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.clientSecret = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.authUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.tokenUrl = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.userInfoUrl = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.fieldMapping = IdentityProviderConfig_FieldMapping.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<IdentityProviderConfig_OAuth2Config>): IdentityProviderConfig_OAuth2Config {
    return IdentityProviderConfig_OAuth2Config.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<IdentityProviderConfig_OAuth2Config>): IdentityProviderConfig_OAuth2Config {
    const message = createBaseIdentityProviderConfig_OAuth2Config();
    message.clientId = object.clientId ?? "";
    message.clientSecret = object.clientSecret ?? "";
    message.authUrl = object.authUrl ?? "";
    message.tokenUrl = object.tokenUrl ?? "";
    message.userInfoUrl = object.userInfoUrl ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.fieldMapping = (object.fieldMapping !== undefined && object.fieldMapping !== null)
      ? IdentityProviderConfig_FieldMapping.fromPartial(object.fieldMapping)
      : undefined;
    return message;
  },
};

function createBaseGetWorkspaceProfileRequest(): GetWorkspaceProfileRequest {
  return {};
}

export const GetWorkspaceProfileRequest: MessageFns<GetWorkspaceProfileRequest> = {
  encode(_: GetWorkspaceProfileRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceProfileRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceProfileRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetWorkspaceProfileRequest>): GetWorkspaceProfileRequest {
    return GetWorkspaceProfileRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetWorkspaceProfileRequest>): GetWorkspaceProfileRequest {
    const message = createBaseGetWorkspaceProfileRequest();
    return message;
  },
};

function createBaseGetWorkspaceSettingRequest(): GetWorkspaceSettingRequest {
  return {};
}

export const GetWorkspaceSettingRequest: MessageFns<GetWorkspaceSettingRequest> = {
  encode(_: GetWorkspaceSettingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceSettingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceSettingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetWorkspaceSettingRequest>): GetWorkspaceSettingRequest {
    return GetWorkspaceSettingRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetWorkspaceSettingRequest>): GetWorkspaceSettingRequest {
    const message = createBaseGetWorkspaceSettingRequest();
    return message;
  },
};

function createBaseUpdateWorkspaceSettingRequest(): UpdateWorkspaceSettingRequest {
  return { setting: undefined, updateMask: undefined };
}

export const UpdateWorkspaceSettingRequest: MessageFns<UpdateWorkspaceSettingRequest> = {
  encode(message: UpdateWorkspaceSettingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.setting !== undefined) {
      WorkspaceSetting.encode(message.setting, writer.uint32(10).fork()).join();
    }
    if (message.updateMask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.updateMask), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWorkspaceSettingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWorkspaceSettingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.setting = WorkspaceSetting.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.updateMask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<UpdateWorkspaceSettingRequest>): UpdateWorkspaceSettingRequest {
    return UpdateWorkspaceSettingRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateWorkspaceSettingRequest>): UpdateWorkspaceSettingRequest {
    const message = createBaseUpdateWorkspaceSettingRequest();
    message.setting = (object.setting !== undefined && object.setting !== null)
      ? WorkspaceSetting.fromPartial(object.setting)
      : undefined;
    message.updateMask = object.updateMask ?? undefined;
    return message;
  },
};

function createBaseGetWorkspaceStatsRequest(): GetWorkspaceStatsRequest {
  return {};
}

export const GetWorkspaceStatsRequest: MessageFns<GetWorkspaceStatsRequest> = {
  encode(_: GetWorkspaceStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetWorkspaceStatsRequest>): GetWorkspaceStatsRequest {
    return GetWorkspaceStatsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetWorkspaceStatsRequest>): GetWorkspaceStatsRequest {
    const message = createBaseGetWorkspaceStatsRequest();
    return message;
  },
};

function createBaseWorkspaceStats(): WorkspaceStats {
  return { totalShortcuts: 0, totalUsers: 0, totalCollections: 0, totalHits: 0, historicalData: [] };
}

export const WorkspaceStats: MessageFns<WorkspaceStats> = {
  encode(message: WorkspaceStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalShortcuts !== 0) {
      writer.uint32(8).int32(message.totalShortcuts);
    }
    if (message.totalUsers !== 0) {
      writer.uint32(16).int32(message.totalUsers);
    }
    if (message.totalCollections !== 0) {
      writer.uint32(24).int32(message.totalCollections);
    }
    if (message.totalHits !== 0) {
      writer.uint32(32).int32(message.totalHits);
    }
    for (const v of message.historicalData) {
      StatsMeasurement.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkspaceStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkspaceStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalShortcuts = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalUsers = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalCollections = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalHits = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.historicalData.push(StatsMeasurement.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<WorkspaceStats>): WorkspaceStats {
    return WorkspaceStats.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<WorkspaceStats>): WorkspaceStats {
    const message = createBaseWorkspaceStats();
    message.totalShortcuts = object.totalShortcuts ?? 0;
    message.totalUsers = object.totalUsers ?? 0;
    message.totalCollections = object.totalCollections ?? 0;
    message.totalHits = object.totalHits ?? 0;
    message.historicalData = object.historicalData?.map((e) => StatsMeasurement.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStatsMeasurement(): StatsMeasurement {
  return { measuredTs: 0, shortcutsCount: 0, usersCount: 0, collectionsCount: 0, hitsCount: 0 };
}

export const StatsMeasurement: MessageFns<StatsMeasurement> = {
  encode(message: StatsMeasurement, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.measuredTs !== 0) {
      writer.uint32(8).int64(message.measuredTs);
    }
    if (message.shortcutsCount !== 0) {
      writer.uint32(16).int32(message.shortcutsCount);
    }
    if (message.usersCount !== 0) {
      writer.uint32(24).int32(message.usersCount);
    }
    if (message.collectionsCount !== 0) {
      writer.uint32(32).int32(message.collectionsCount);
    }
    if (message.hitsCount !== 0) {
      writer.uint32(40).int32(message.hitsCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatsMeasurement {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatsMeasurement();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.measuredTs = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shortcutsCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.usersCount = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.collectionsCount = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.hitsCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StatsMeasurement>): StatsMeasurement {
    return StatsMeasurement.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StatsMeasurement>): StatsMeasurement {
    const message = createBaseStatsMeasurement();
    message.measuredTs = object.measuredTs ?? 0;
    message.shortcutsCount = object.shortcutsCount ?? 0;
    message.usersCount = object.usersCount ?? 0;
    message.collectionsCount = object.collectionsCount ?? 0;
    message.hitsCount = object.hitsCount ?? 0;
    return message;
  },
};

function createBaseGetDatabaseStatsRequest(): GetDatabaseStatsRequest {
  return {};
}

export const GetDatabaseStatsRequest: MessageFns<GetDatabaseStatsRequest> = {
  encode(_: GetDatabaseStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDatabaseStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDatabaseStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDatabaseStatsRequest>): GetDatabaseStatsRequest {
    return GetDatabaseStatsRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetDatabaseStatsRequest>): GetDatabaseStatsRequest {
    const message = createBaseGetDatabaseStatsRequest();
    return message;
  },
};

function createBaseDatabaseStats(): DatabaseStats {
  return {
    users: 0,
    shortcuts: 0,
    collections: 0,
    tags: 0,
    bookmarkTags: 0,
    friendships: 0,
    followings: 0,
    activities: 0,
    invitations: 0,
  };
}

export const DatabaseStats: MessageFns<DatabaseStats> = {
  encode(message: DatabaseStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.users !== 0) {
      writer.uint32(8).int32(message.users);
    }
    if (message.shortcuts !== 0) {
      writer.uint32(16).int32(message.shortcuts);
    }
    if (message.collections !== 0) {
      writer.uint32(24).int32(message.collections);
    }
    if (message.tags !== 0) {
      writer.uint32(32).int32(message.tags);
    }
    if (message.bookmarkTags !== 0) {
      writer.uint32(40).int32(message.bookmarkTags);
    }
    if (message.friendships !== 0) {
      writer.uint32(48).int32(message.friendships);
    }
    if (message.followings !== 0) {
      writer.uint32(56).int32(message.followings);
    }
    if (message.activities !== 0) {
      writer.uint32(64).int32(message.activities);
    }
    if (message.invitations !== 0) {
      writer.uint32(72).int32(message.invitations);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DatabaseStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDatabaseStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.users = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.shortcuts = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.collections = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.tags = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.bookmarkTags = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.friendships = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.followings = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.activities = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.invitations = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<DatabaseStats>): DatabaseStats {
    return DatabaseStats.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DatabaseStats>): DatabaseStats {
    const message = createBaseDatabaseStats();
    message.users = object.users ?? 0;
    message.shortcuts = object.shortcuts ?? 0;
    message.collections = object.collections ?? 0;
    message.tags = object.tags ?? 0;
    message.bookmarkTags = object.bookmarkTags ?? 0;
    message.friendships = object.friendships ?? 0;
    message.followings = object.followings ?? 0;
    message.activities = object.activities ?? 0;
    message.invitations = object.invitations ?? 0;
    return message;
  },
};

function createBaseExportDatabaseRequest(): ExportDatabaseRequest {
  return { entities: [] };
}

export const ExportDatabaseRequest: MessageFns<ExportDatabaseRequest> = {
  encode(message: ExportDatabaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.entities) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportDatabaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDatabaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entities.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ExportDatabaseRequest>): ExportDatabaseRequest {
    return ExportDatabaseRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExportDatabaseRequest>): ExportDatabaseRequest {
    const message = createBaseExportDatabaseRequest();
    message.entities = object.entities?.map((e) => e) || [];
    return message;
  },
};

function createBaseExportDatabaseResponse(): ExportDatabaseResponse {
  return { data: "", filename: "" };
}

export const ExportDatabaseResponse: MessageFns<ExportDatabaseResponse> = {
  encode(message: ExportDatabaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExportDatabaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExportDatabaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ExportDatabaseResponse>): ExportDatabaseResponse {
    return ExportDatabaseResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ExportDatabaseResponse>): ExportDatabaseResponse {
    const message = createBaseExportDatabaseResponse();
    message.data = object.data ?? "";
    message.filename = object.filename ?? "";
    return message;
  },
};

function createBaseImportDatabaseRequest(): ImportDatabaseRequest {
  return { data: "", entities: [], mode: "" };
}

export const ImportDatabaseRequest: MessageFns<ImportDatabaseRequest> = {
  encode(message: ImportDatabaseRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.data !== "") {
      writer.uint32(10).string(message.data);
    }
    for (const v of message.entities) {
      writer.uint32(18).string(v!);
    }
    if (message.mode !== "") {
      writer.uint32(26).string(message.mode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImportDatabaseRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImportDatabaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.entities.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.mode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ImportDatabaseRequest>): ImportDatabaseRequest {
    return ImportDatabaseRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ImportDatabaseRequest>): ImportDatabaseRequest {
    const message = createBaseImportDatabaseRequest();
    message.data = object.data ?? "";
    message.entities = object.entities?.map((e) => e) || [];
    message.mode = object.mode ?? "";
    return message;
  },
};

function createBaseImportDatabaseResponse(): ImportDatabaseResponse {
  return { importedCounts: {}, messages: [] };
}

export const ImportDatabaseResponse: MessageFns<ImportDatabaseResponse> = {
  encode(message: ImportDatabaseResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.importedCounts).forEach(([key, value]: [string, number]) => {
      ImportDatabaseResponse_ImportedCountsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    for (const v of message.messages) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImportDatabaseResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImportDatabaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = ImportDatabaseResponse_ImportedCountsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.importedCounts[entry1.key] = entry1.value;
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messages.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ImportDatabaseResponse>): ImportDatabaseResponse {
    return ImportDatabaseResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ImportDatabaseResponse>): ImportDatabaseResponse {
    const message = createBaseImportDatabaseResponse();
    message.importedCounts = (globalThis.Object.entries(object.importedCounts ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.messages = object.messages?.map((e) => e) || [];
    return message;
  },
};

function createBaseImportDatabaseResponse_ImportedCountsEntry(): ImportDatabaseResponse_ImportedCountsEntry {
  return { key: "", value: 0 };
}

export const ImportDatabaseResponse_ImportedCountsEntry: MessageFns<ImportDatabaseResponse_ImportedCountsEntry> = {
  encode(message: ImportDatabaseResponse_ImportedCountsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).int32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ImportDatabaseResponse_ImportedCountsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseImportDatabaseResponse_ImportedCountsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ImportDatabaseResponse_ImportedCountsEntry>): ImportDatabaseResponse_ImportedCountsEntry {
    return ImportDatabaseResponse_ImportedCountsEntry.fromPartial(base ?? {});
  },
  fromPartial(
    object: DeepPartial<ImportDatabaseResponse_ImportedCountsEntry>,
  ): ImportDatabaseResponse_ImportedCountsEntry {
    const message = createBaseImportDatabaseResponse_ImportedCountsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseGetDatabaseReportRequest(): GetDatabaseReportRequest {
  return { entity: "", limit: undefined, offset: undefined };
}

export const GetDatabaseReportRequest: MessageFns<GetDatabaseReportRequest> = {
  encode(message: GetDatabaseReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity !== "") {
      writer.uint32(10).string(message.entity);
    }
    if (message.limit !== undefined) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.offset !== undefined) {
      writer.uint32(24).int32(message.offset);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDatabaseReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDatabaseReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDatabaseReportRequest>): GetDatabaseReportRequest {
    return GetDatabaseReportRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDatabaseReportRequest>): GetDatabaseReportRequest {
    const message = createBaseGetDatabaseReportRequest();
    message.entity = object.entity ?? "";
    message.limit = object.limit ?? undefined;
    message.offset = object.offset ?? undefined;
    return message;
  },
};

function createBaseGetDatabaseReportResponse(): GetDatabaseReportResponse {
  return { entity: "", totalCount: 0, data: "", metadata: {} };
}

export const GetDatabaseReportResponse: MessageFns<GetDatabaseReportResponse> = {
  encode(message: GetDatabaseReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.entity !== "") {
      writer.uint32(10).string(message.entity);
    }
    if (message.totalCount !== 0) {
      writer.uint32(16).int32(message.totalCount);
    }
    if (message.data !== "") {
      writer.uint32(26).string(message.data);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      GetDatabaseReportResponse_MetadataEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDatabaseReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDatabaseReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.entity = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalCount = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = GetDatabaseReportResponse_MetadataEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.metadata[entry4.key] = entry4.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDatabaseReportResponse>): GetDatabaseReportResponse {
    return GetDatabaseReportResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDatabaseReportResponse>): GetDatabaseReportResponse {
    const message = createBaseGetDatabaseReportResponse();
    message.entity = object.entity ?? "";
    message.totalCount = object.totalCount ?? 0;
    message.data = object.data ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseGetDatabaseReportResponse_MetadataEntry(): GetDatabaseReportResponse_MetadataEntry {
  return { key: "", value: "" };
}

export const GetDatabaseReportResponse_MetadataEntry: MessageFns<GetDatabaseReportResponse_MetadataEntry> = {
  encode(message: GetDatabaseReportResponse_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetDatabaseReportResponse_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetDatabaseReportResponse_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetDatabaseReportResponse_MetadataEntry>): GetDatabaseReportResponse_MetadataEntry {
    return GetDatabaseReportResponse_MetadataEntry.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetDatabaseReportResponse_MetadataEntry>): GetDatabaseReportResponse_MetadataEntry {
    const message = createBaseGetDatabaseReportResponse_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

export type WorkspaceServiceDefinition = typeof WorkspaceServiceDefinition;
export const WorkspaceServiceDefinition = {
  name: "WorkspaceService",
  fullName: "monotreme.api.v1.WorkspaceService",
  methods: {
    getWorkspaceProfile: {
      name: "GetWorkspaceProfile",
      requestType: GetWorkspaceProfileRequest,
      requestStream: false,
      responseType: WorkspaceProfile,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              27,
              18,
              25,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              112,
              114,
              111,
              102,
              105,
              108,
              101,
            ]),
          ],
        },
      },
    },
    getWorkspaceSetting: {
      name: "GetWorkspaceSetting",
      requestType: GetWorkspaceSettingRequest,
      requestStream: false,
      responseType: WorkspaceSetting,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              27,
              18,
              25,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              115,
              101,
              116,
              116,
              105,
              110,
              103,
            ]),
          ],
        },
      },
    },
    updateWorkspaceSetting: {
      name: "UpdateWorkspaceSetting",
      requestType: UpdateWorkspaceSettingRequest,
      requestStream: false,
      responseType: WorkspaceSetting,
      responseStream: false,
      options: {
        _unknownFields: {
          8410: [
            new Uint8Array([
              19,
              115,
              101,
              116,
              116,
              105,
              110,
              103,
              44,
              117,
              112,
              100,
              97,
              116,
              101,
              95,
              109,
              97,
              115,
              107,
            ]),
          ],
          578365826: [
            new Uint8Array([
              36,
              58,
              7,
              115,
              101,
              116,
              116,
              105,
              110,
              103,
              50,
              25,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              115,
              101,
              116,
              116,
              105,
              110,
              103,
            ]),
          ],
        },
      },
    },
    getWorkspaceStats: {
      name: "GetWorkspaceStats",
      requestType: GetWorkspaceStatsRequest,
      requestStream: false,
      responseType: WorkspaceStats,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              25,
              18,
              23,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              115,
              116,
              97,
              116,
              115,
            ]),
          ],
        },
      },
    },
    getDatabaseStats: {
      name: "GetDatabaseStats",
      requestType: GetDatabaseStatsRequest,
      requestStream: false,
      responseType: DatabaseStats,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              34,
              18,
              32,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              100,
              97,
              116,
              97,
              98,
              97,
              115,
              101,
              47,
              115,
              116,
              97,
              116,
              115,
            ]),
          ],
        },
      },
    },
    exportDatabase: {
      name: "ExportDatabase",
      requestType: ExportDatabaseRequest,
      requestStream: false,
      responseType: ExportDatabaseResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              38,
              58,
              1,
              42,
              34,
              33,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              100,
              97,
              116,
              97,
              98,
              97,
              115,
              101,
              47,
              101,
              120,
              112,
              111,
              114,
              116,
            ]),
          ],
        },
      },
    },
    importDatabase: {
      name: "ImportDatabase",
      requestType: ImportDatabaseRequest,
      requestStream: false,
      responseType: ImportDatabaseResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              38,
              58,
              1,
              42,
              34,
              33,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              100,
              97,
              116,
              97,
              98,
              97,
              115,
              101,
              47,
              105,
              109,
              112,
              111,
              114,
              116,
            ]),
          ],
        },
      },
    },
    getDatabaseReport: {
      name: "GetDatabaseReport",
      requestType: GetDatabaseReportRequest,
      requestStream: false,
      responseType: GetDatabaseReportResponse,
      responseStream: false,
      options: {
        _unknownFields: {
          578365826: [
            new Uint8Array([
              44,
              18,
              42,
              47,
              97,
              112,
              105,
              47,
              118,
              49,
              47,
              119,
              111,
              114,
              107,
              115,
              112,
              97,
              99,
              101,
              47,
              100,
              97,
              116,
              97,
              98,
              97,
              115,
              101,
              47,
              114,
              101,
              112,
              111,
              114,
              116,
              47,
              123,
              101,
              110,
              116,
              105,
              116,
              121,
              125,
            ]),
          ],
        },
      },
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
