// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: store/bookmark_tag.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "monotreme.store";

export interface BookmarkTag {
  shortcutId: number;
  tagUuid: string;
  userId: number;
  createdTs: number;
}

function createBaseBookmarkTag(): BookmarkTag {
  return { shortcutId: 0, tagUuid: "", userId: 0, createdTs: 0 };
}

export const BookmarkTag: MessageFns<BookmarkTag> = {
  encode(message: BookmarkTag, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.shortcutId !== 0) {
      writer.uint32(8).int32(message.shortcutId);
    }
    if (message.tagUuid !== "") {
      writer.uint32(18).string(message.tagUuid);
    }
    if (message.userId !== 0) {
      writer.uint32(24).int32(message.userId);
    }
    if (message.createdTs !== 0) {
      writer.uint32(32).int64(message.createdTs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BookmarkTag {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBookmarkTag();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.shortcutId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tagUuid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.userId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.createdTs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BookmarkTag>): BookmarkTag {
    return BookmarkTag.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BookmarkTag>): BookmarkTag {
    const message = createBaseBookmarkTag();
    message.shortcutId = object.shortcutId ?? 0;
    message.tagUuid = object.tagUuid ?? "";
    message.userId = object.userId ?? 0;
    message.createdTs = object.createdTs ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
