// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: store/common.proto

/* eslint-disable */

export const protobufPackage = "monotreme.store";

export enum RowStatus {
  ROW_STATUS_UNSPECIFIED = "ROW_STATUS_UNSPECIFIED",
  NORMAL = "NORMAL",
  ARCHIVED = "ARCHIVED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function rowStatusFromJSON(object: any): RowStatus {
  switch (object) {
    case 0:
    case "ROW_STATUS_UNSPECIFIED":
      return RowStatus.ROW_STATUS_UNSPECIFIED;
    case 1:
    case "NORMAL":
      return RowStatus.NORMAL;
    case 2:
    case "ARCHIVED":
      return RowStatus.ARCHIVED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RowStatus.UNRECOGNIZED;
  }
}

export function rowStatusToNumber(object: RowStatus): number {
  switch (object) {
    case RowStatus.ROW_STATUS_UNSPECIFIED:
      return 0;
    case RowStatus.NORMAL:
      return 1;
    case RowStatus.ARCHIVED:
      return 2;
    case RowStatus.UNRECOGNIZED:
    default:
      return -1;
  }
}

export enum Visibility {
  VISIBILITY_UNSPECIFIED = "VISIBILITY_UNSPECIFIED",
  WORKSPACE = "WORKSPACE",
  PUBLIC = "PUBLIC",
  PRIVATE = "PRIVATE",
  FRIENDS = "FRIENDS",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export function visibilityFromJSON(object: any): Visibility {
  switch (object) {
    case 0:
    case "VISIBILITY_UNSPECIFIED":
      return Visibility.VISIBILITY_UNSPECIFIED;
    case 1:
    case "WORKSPACE":
      return Visibility.WORKSPACE;
    case 2:
    case "PUBLIC":
      return Visibility.PUBLIC;
    case 3:
    case "PRIVATE":
      return Visibility.PRIVATE;
    case 4:
    case "FRIENDS":
      return Visibility.FRIENDS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Visibility.UNRECOGNIZED;
  }
}

export function visibilityToNumber(object: Visibility): number {
  switch (object) {
    case Visibility.VISIBILITY_UNSPECIFIED:
      return 0;
    case Visibility.WORKSPACE:
      return 1;
    case Visibility.PUBLIC:
      return 2;
    case Visibility.PRIVATE:
      return 3;
    case Visibility.FRIENDS:
      return 4;
    case Visibility.UNRECOGNIZED:
    default:
      return -1;
  }
}
