// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.0
//   protoc               unknown
// source: store/rss_feed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import {
  RowStatus,
  rowStatusFromJSON,
  rowStatusToNumber,
  Visibility,
  visibilityFromJSON,
  visibilityToNumber,
} from "./common";

export const protobufPackage = "monotreme.store";

export interface RssFeed {
  id: number;
  uuid: string;
  creatorId: number;
  createdTs?: Date | undefined;
  updatedTs?: Date | undefined;
  title: string;
  url: string;
  description: string;
  /** Import settings */
  autoImport: boolean;
  importFrequencyHours: number;
  lastImportTs?:
    | Date
    | undefined;
  /** Shortcut generation settings */
  defaultTags: string[];
  defaultVisibility: Visibility;
  shortcutPrefix: string;
  /** Status */
  isActive: boolean;
  lastError: string;
  totalImported: number;
  rowStatus: RowStatus;
}

/**
 * Stores information about RSS items that have been processed
 * to avoid duplicate imports
 */
export interface RssFeedItem {
  id: number;
  uuid: string;
  rssFeedId: number;
  createdTs?:
    | Date
    | undefined;
  /** RSS item identification */
  itemGuid: string;
  itemLink: string;
  itemTitle: string;
  itemDescription: string;
  itemPublishedTs?:
    | Date
    | undefined;
  /** Generated shortcut info */
  shortcutId: number;
  importSuccess: boolean;
  importError: string;
  rowStatus: RowStatus;
}

function createBaseRssFeed(): RssFeed {
  return {
    id: 0,
    uuid: "",
    creatorId: 0,
    createdTs: undefined,
    updatedTs: undefined,
    title: "",
    url: "",
    description: "",
    autoImport: false,
    importFrequencyHours: 0,
    lastImportTs: undefined,
    defaultTags: [],
    defaultVisibility: Visibility.VISIBILITY_UNSPECIFIED,
    shortcutPrefix: "",
    isActive: false,
    lastError: "",
    totalImported: 0,
    rowStatus: RowStatus.ROW_STATUS_UNSPECIFIED,
  };
}

export const RssFeed: MessageFns<RssFeed> = {
  encode(message: RssFeed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.uuid !== "") {
      writer.uint32(18).string(message.uuid);
    }
    if (message.creatorId !== 0) {
      writer.uint32(24).int32(message.creatorId);
    }
    if (message.createdTs !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTs), writer.uint32(34).fork()).join();
    }
    if (message.updatedTs !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedTs), writer.uint32(42).fork()).join();
    }
    if (message.title !== "") {
      writer.uint32(50).string(message.title);
    }
    if (message.url !== "") {
      writer.uint32(58).string(message.url);
    }
    if (message.description !== "") {
      writer.uint32(66).string(message.description);
    }
    if (message.autoImport !== false) {
      writer.uint32(72).bool(message.autoImport);
    }
    if (message.importFrequencyHours !== 0) {
      writer.uint32(80).int32(message.importFrequencyHours);
    }
    if (message.lastImportTs !== undefined) {
      Timestamp.encode(toTimestamp(message.lastImportTs), writer.uint32(90).fork()).join();
    }
    for (const v of message.defaultTags) {
      writer.uint32(98).string(v!);
    }
    if (message.defaultVisibility !== Visibility.VISIBILITY_UNSPECIFIED) {
      writer.uint32(104).int32(visibilityToNumber(message.defaultVisibility));
    }
    if (message.shortcutPrefix !== "") {
      writer.uint32(114).string(message.shortcutPrefix);
    }
    if (message.isActive !== false) {
      writer.uint32(120).bool(message.isActive);
    }
    if (message.lastError !== "") {
      writer.uint32(130).string(message.lastError);
    }
    if (message.totalImported !== 0) {
      writer.uint32(136).int32(message.totalImported);
    }
    if (message.rowStatus !== RowStatus.ROW_STATUS_UNSPECIFIED) {
      writer.uint32(144).int32(rowStatusToNumber(message.rowStatus));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RssFeed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRssFeed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.creatorId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdTs = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updatedTs = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.autoImport = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.importFrequencyHours = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.lastImportTs = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.defaultTags.push(reader.string());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.defaultVisibility = visibilityFromJSON(reader.int32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.shortcutPrefix = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.lastError = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.totalImported = reader.int32();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.rowStatus = rowStatusFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RssFeed>): RssFeed {
    return RssFeed.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RssFeed>): RssFeed {
    const message = createBaseRssFeed();
    message.id = object.id ?? 0;
    message.uuid = object.uuid ?? "";
    message.creatorId = object.creatorId ?? 0;
    message.createdTs = object.createdTs ?? undefined;
    message.updatedTs = object.updatedTs ?? undefined;
    message.title = object.title ?? "";
    message.url = object.url ?? "";
    message.description = object.description ?? "";
    message.autoImport = object.autoImport ?? false;
    message.importFrequencyHours = object.importFrequencyHours ?? 0;
    message.lastImportTs = object.lastImportTs ?? undefined;
    message.defaultTags = object.defaultTags?.map((e) => e) || [];
    message.defaultVisibility = object.defaultVisibility ?? Visibility.VISIBILITY_UNSPECIFIED;
    message.shortcutPrefix = object.shortcutPrefix ?? "";
    message.isActive = object.isActive ?? false;
    message.lastError = object.lastError ?? "";
    message.totalImported = object.totalImported ?? 0;
    message.rowStatus = object.rowStatus ?? RowStatus.ROW_STATUS_UNSPECIFIED;
    return message;
  },
};

function createBaseRssFeedItem(): RssFeedItem {
  return {
    id: 0,
    uuid: "",
    rssFeedId: 0,
    createdTs: undefined,
    itemGuid: "",
    itemLink: "",
    itemTitle: "",
    itemDescription: "",
    itemPublishedTs: undefined,
    shortcutId: 0,
    importSuccess: false,
    importError: "",
    rowStatus: RowStatus.ROW_STATUS_UNSPECIFIED,
  };
}

export const RssFeedItem: MessageFns<RssFeedItem> = {
  encode(message: RssFeedItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.uuid !== "") {
      writer.uint32(18).string(message.uuid);
    }
    if (message.rssFeedId !== 0) {
      writer.uint32(24).int32(message.rssFeedId);
    }
    if (message.createdTs !== undefined) {
      Timestamp.encode(toTimestamp(message.createdTs), writer.uint32(34).fork()).join();
    }
    if (message.itemGuid !== "") {
      writer.uint32(42).string(message.itemGuid);
    }
    if (message.itemLink !== "") {
      writer.uint32(50).string(message.itemLink);
    }
    if (message.itemTitle !== "") {
      writer.uint32(58).string(message.itemTitle);
    }
    if (message.itemDescription !== "") {
      writer.uint32(66).string(message.itemDescription);
    }
    if (message.itemPublishedTs !== undefined) {
      Timestamp.encode(toTimestamp(message.itemPublishedTs), writer.uint32(74).fork()).join();
    }
    if (message.shortcutId !== 0) {
      writer.uint32(80).int32(message.shortcutId);
    }
    if (message.importSuccess !== false) {
      writer.uint32(88).bool(message.importSuccess);
    }
    if (message.importError !== "") {
      writer.uint32(98).string(message.importError);
    }
    if (message.rowStatus !== RowStatus.ROW_STATUS_UNSPECIFIED) {
      writer.uint32(104).int32(rowStatusToNumber(message.rowStatus));
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RssFeedItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRssFeedItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uuid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rssFeedId = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdTs = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.itemGuid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.itemLink = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.itemTitle = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.itemDescription = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.itemPublishedTs = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.shortcutId = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.importSuccess = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.importError = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.rowStatus = rowStatusFromJSON(reader.int32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<RssFeedItem>): RssFeedItem {
    return RssFeedItem.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RssFeedItem>): RssFeedItem {
    const message = createBaseRssFeedItem();
    message.id = object.id ?? 0;
    message.uuid = object.uuid ?? "";
    message.rssFeedId = object.rssFeedId ?? 0;
    message.createdTs = object.createdTs ?? undefined;
    message.itemGuid = object.itemGuid ?? "";
    message.itemLink = object.itemLink ?? "";
    message.itemTitle = object.itemTitle ?? "";
    message.itemDescription = object.itemDescription ?? "";
    message.itemPublishedTs = object.itemPublishedTs ?? undefined;
    message.shortcutId = object.shortcutId ?? 0;
    message.importSuccess = object.importSuccess ?? false;
    message.importError = object.importError ?? "";
    message.rowStatus = object.rowStatus ?? RowStatus.ROW_STATUS_UNSPECIFIED;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
